#!/bin/bash

# Mobile vs Web - Data Loading Debug Checklist

echo "═══════════════════════════════════════════════════════════════════"
echo "  MOBILE APP MY REMINDERS - DEBUG CHECKLIST"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

echo "✅ STEP 1: Prepare Your Setup"
echo "─────────────────────────────"
echo "□ Android device/emulator connected"
echo "□ App built: npx react-native run-android"
echo "□ Android Studio Logcat open"
echo "□ Admin account logged in"
echo ""

echo "✅ STEP 2: Navigate to My Reminders"
echo "────────────────────────────────────"
echo "□ Open app drawer menu"
echo "□ Tap 'Admin My Reminders' (alarm icon)"
echo "□ Watch Logcat for logs"
echo ""

echo "✅ STEP 3: Watch for These Logs (in order)"
echo "───────────────────────────────────────────"
echo ""
echo "First Log:"
echo "  🚀 AdminMyReminders initializing..."
echo "  Status: Should appear immediately"
echo ""
echo "Second Log:"
echo "  ✅ Token found, starting data fetch..."
echo "  Status: Token should be found"
echo "  If ❌: Login token is missing/expired"
echo ""
echo "Third Log (Parallel fetches):"
echo "  📊 Fetching stats with token..."
echo "  👥 Fetching employees..."
echo "  ⏰ Fetching due reminders..."
echo "  Status: All three should appear"
echo ""
echo "Final Logs:"
echo "  ✅ Stats response success: true"
echo "  ✅ Employees response success: true"
echo "  ✅ Due reminders response success: true"
echo "  Status: All should be true"
echo ""

echo "✅ STEP 4: Check Data Loading"
echo "──────────────────────────────"
echo "□ Overview tab: Stats cards populated"
echo "□ Employees tab: List shows employees"
echo "□ Due Reminders tab: Shows due items"
echo ""

echo "✅ STEP 5: If Data NOT Showing"
echo "───────────────────────────────"
echo ""
echo "Look for ERROR logs:"
echo "  ❌ Error fetching stats: [error message]"
echo "  Response status: [HTTP code]"
echo "  Response data: [API error]"
echo ""
echo "Common HTTP Status Codes:"
echo "  401: Token invalid - Login again"
echo "  404: Endpoint not found - Backend issue"
echo "  500: Server error - Check backend logs"
echo "  200: Success - Check if data is empty"
echo ""

echo "✅ STEP 6: Debug Information to Collect"
echo "────────────────────────────────────────"
echo "If you need help, collect:"
echo "  1. Full Logcat output (copy from Android Studio)"
echo "  2. What HTTP status you see (if any)"
echo "  3. Response message from API (if any)"
echo "  4. Screenshot of empty screen"
echo ""

echo "✅ STEP 7: Test API Directly"
echo "──────────────────────────────"
echo "Run: cd backend && node test-admin-reminders-mobile.mjs"
echo "This will:"
echo "  - Login with admin credentials"
echo "  - Test all three API endpoints"
echo "  - Show actual responses from backend"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "  CONSOLE LOG FORMAT GUIDE"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✅ = Success - Everything working"
echo "❌ = Error - Something failed"
echo "⏳ = In progress - Waiting for response"
echo "📊 = Statistics"
echo "👥 = Employees"
echo "⏰ = Due reminders"
echo "🔍 = Searching/checking"
echo "⚠️  = Warning"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "  QUICK TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "No logs appear at all?"
echo "  → Check your Logcat filter"
echo "  → Try: adb logcat | grep React"
echo ""
echo "401 errors?"
echo "  → Session expired - logout and login again"
echo "  → Run: AsyncStorage.clear() in dev menu"
echo ""
echo "500 errors?"
echo "  → Backend problem"
echo "  → Check backend/server.js is running"
echo "  → Look at backend logs"
echo ""
echo "0 items showing?"
echo "  → No data in database"
echo "  → Check web version - does it show data?"
echo "  → Add test reminders via web interface"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
